apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: java-route
spec:
  to:
    kind: Service
    name: java-app-service
  port:
    targetPort: 8081
  tls:
    termination: edge
  wildcardPolicy: None